#if UNITY_EDITOR
using System.Globalization;
using System.Text;

/// <summary>
/// Pure config-to-JS generator for the LUIDA DataCollector calculator script.
///
/// Always emits the auto-generated CCK sync header (mirrors registered
/// CCK-eligible labels from CCK global state into $.groupState.collectedData
/// and shadows COLLECTED_DATA inside saveData() — see §16.1 of the GUI plan).
///
/// In Builder mode, emits `const fields = { ... }` from the config's `fields`
/// list and then `return fields;`.
///
/// In Code mode, emits the user's `rawJs` verbatim after the header.
///
/// The output is intended to be written verbatim as the calculator JS asset
/// at Assets/_Experiment_/Scripts/DataCollectors/{SceneName}.js. The
/// surrounding wrapper (function calculateData() { ... function saveData()
/// { &lt;THIS&gt; } returnData.push(saveData()); ... }) is supplied at combine
/// time by CustomDataUploader.js.
/// </summary>
public static class LuidaDataCollectorJsGenerator
{
    public const string AutoGenStartMarker = "// === LUIDA AUTO-GENERATED (do not edit between markers) ===";
    public const string AutoGenEndMarker   = "// === LUIDA AUTO-GENERATED END ===";

    /// <summary>
    /// Name of the synthetic field that gets auto-injected into the generated
    /// `fields` dict (Builder mode) whenever the LUIDA automation feature is
    /// active for the current scene. Surfaces the state-transition record
    /// populated by Runtime/ExpSettings/StateLogger.js at
    /// $.groupState.collectedData["stateLog"].
    ///
    /// Kept public so the config tab can use the same name when warning the
    /// user about a manual field that would collide with this injection.
    /// </summary>
    public const string AutoStateLogFieldName = "stateLog";

    public static string Generate(LuidaDataCollectorConfig config)
    {
        var sb = new StringBuilder();
        AppendAutoGeneratedHeader(sb, config);

        if (config == null)
        {
            sb.Append("return {};\n");
            return sb.ToString();
        }

        bool automationActive = LuidaAutomationStatus.IsActiveForActiveScene();

        if (config.useCustomCodeMode)
        {
            if (automationActive) AppendStateLogCodeModeHint(sb);
            string body = config.rawJs ?? string.Empty;
            sb.Append(body);
            if (!body.EndsWith("\n")) sb.Append('\n');
        }
        else
        {
            AppendFieldDictionary(sb, config, automationActive);
            sb.Append("return fields;\n");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Generate just the Builder-mode body (no auto-gen sync header). Used as
    /// the seed for rawJs when switching Builder → Code mode so the header
    /// isn't duplicated on the next save (Generate() always re-prepends it).
    /// </summary>
    public static string GenerateBuilderBodyOnly(LuidaDataCollectorConfig config)
    {
        if (config == null) return "return {};\n";
        var sb = new StringBuilder();
        AppendFieldDictionary(sb, config, LuidaAutomationStatus.IsActiveForActiveScene());
        sb.Append("return fields;\n");
        return sb.ToString();
    }

    /// <summary>
    /// True when the user has manually added a field whose name collides with
    /// the auto-injected state-log entry. When this is true the generator
    /// skips auto-injection (the user's expression wins) and the config tab
    /// surfaces a warning.
    /// </summary>
    public static bool HasUserStateLogField(LuidaDataCollectorConfig config)
    {
        if (config == null || config.fields == null) return false;
        foreach (var f in config.fields)
        {
            if (f == null) continue;
            if (string.Equals(f.fieldName, AutoStateLogFieldName, System.StringComparison.Ordinal))
                return true;
        }
        return false;
    }

    // ─────────────────────────── Header ───────────────────────────

    static void AppendAutoGeneratedHeader(StringBuilder sb, LuidaDataCollectorConfig config)
    {
        sb.Append(AutoGenStartMarker).Append('\n');
        sb.Append("// Regenerated from LuidaDataCollectorConfig — manual edits inside this block will be lost.\n");

        bool hasCckLabels = false;
        if (config != null)
        {
            foreach (var l in config.collectedLabels)
            {
                if (l == null || string.IsNullOrEmpty(l.label)) continue;
                if (!IsValidFieldName(l.label)) continue;
                if (l.type == CollectedValueType.String) continue; // action-only
                hasCckLabels = true;
                break;
            }
        }

        if (hasCckLabels)
        {
            sb.Append("(function syncFromCck() {\n");
            sb.Append("    if (!$.groupState.collectedData) $.groupState.collectedData = {};\n");
            sb.Append("    const cd = $.groupState.collectedData;\n");
            sb.Append("    let changed = false;\n");

            foreach (var l in config.collectedLabels)
            {
                if (l == null || string.IsNullOrEmpty(l.label)) continue;
                if (!IsValidFieldName(l.label)) continue;
                if (l.type == CollectedValueType.String) continue;

                string label = l.label;
                string stateKey = LuidaSendDataToCollectorGimmick.ComposeStateKey(label);
                string compatType = CompatTypeFromCollected(l.type);
                string equalCheck = EqualityCheckFromCollected(l.type);

                sb.Append("    // Label: ").Append(label)
                  .Append(" (").Append(l.type.ToString()).Append(")\n");
                sb.Append("    {\n");
                sb.Append("        const v = $.getStateCompat(\"global\", \"").Append(stateKey).Append("\", \"").Append(compatType).Append("\");\n");
                sb.Append("        if (v !== undefined && ").Append(string.Format(equalCheck, "cd[\"" + label + "\"]", "v")).Append(") {\n");
                sb.Append("            cd[\"").Append(label).Append("\"] = v; changed = true;\n");
                sb.Append("        }\n");
                sb.Append("    }\n");
            }

            sb.Append("    if (changed) $.groupState.collectedData = cd;\n");
            sb.Append("})();\n");
            sb.Append("// Rebind COLLECTED_DATA so this saveData() call sees just-synced values.\n");
            sb.Append("const COLLECTED_DATA = $.groupState.collectedData;\n");
        }
        else
        {
            sb.Append("// No CCK-eligible labels registered. Add labels in LUIDA → Configure data collector → Collected data items.\n");
        }

        sb.Append(AutoGenEndMarker).Append('\n');
        sb.Append('\n');
    }

    // ─────────────────────────── Field dictionary ───────────────────────────

    static void AppendFieldDictionary(StringBuilder sb, LuidaDataCollectorConfig config, bool automationActive)
    {
        sb.Append("const fields = {\n");

        // Auto-inject the state-machine transition log when automation is
        // active and the user has not manually added a colliding field. The
        // user's field always wins to keep the on-disk JS valid (no duplicate
        // keys); the config tab warns when this collision happens.
        if (automationActive && !HasUserStateLogField(config))
        {
            sb.Append("    // --- LUIDA AUTO: state machine log (auto-included while automation is active) ---\n");
            sb.Append("    ").Append(AutoStateLogFieldName).Append(": ")
              .Append("(typeof COLLECTED_DATA !== \"undefined\" && COLLECTED_DATA) ? COLLECTED_DATA[\"stateLog\"] : undefined")
              .Append(",\n");
            sb.Append("    // --- END LUIDA AUTO ---\n");
        }

        foreach (var f in config.fields)
        {
            if (f == null) continue;
            if (!IsValidFieldName(f.fieldName)) continue;

            string expr = EmitField(f);
            if (expr == null) continue;

            sb.Append("    ").Append(f.fieldName).Append(": ").Append(expr).Append(",\n");
        }
        sb.Append("};\n");
    }

    static void AppendStateLogCodeModeHint(StringBuilder sb)
    {
        sb.Append("// LUIDA tip: automation is active in this scene, so COLLECTED_DATA[\"stateLog\"]\n");
        sb.Append("//            contains the latest state transition ({ id, name, startAt }).\n");
        sb.Append("//            Add `stateLog: COLLECTED_DATA[\"stateLog\"]` to your returned\n");
        sb.Append("//            object below to include it in the uploaded data.\n");
    }

    // ─────────────────────────── Per-source emitters ───────────────────────────

    static string EmitField(DataCollectorField f)
    {
        switch (f.source)
        {
            case DataFieldSourceKind.Collected:
                return EmitCollectedAccess(f.collectedLabel);

            case DataFieldSourceKind.GlobalStateRead:
                return EmitGlobalStateRead(f.globalStateKey, f.globalStateType);

            case DataFieldSourceKind.ConditionLookup:
                return EmitConditionLookup(f.conditionVariableName);

            case DataFieldSourceKind.JsExpression:
                return EmitDirectValue(f.directValueKind, f.jsExpression);

            case DataFieldSourceKind.Arithmetic:
                return EmitArithmetic(f.arithmeticOperands);

            case DataFieldSourceKind.Conditional:
                return EmitConditional(f);
        }
        // Legacy values should have been migrated by now; emit undefined defensively.
        return "undefined";
    }

    static string EmitGlobalStateRead(string key, CckCollectedValueType type)
    {
        if (string.IsNullOrEmpty(key)) return "undefined";
        return string.Format(
            "$.getStateCompat(\"global\", \"{0}\", \"{1}\")",
            EscapeJsString(key), CompatType(type));
    }

    static string EmitConditionLookup(string variableName)
    {
        if (string.IsNullOrEmpty(variableName)) return "undefined";
        return "CONDITION[\"" + EscapeJsString(variableName) + "\"]";
    }

    static string EmitCollectedAccess(string label)
    {
        if (string.IsNullOrEmpty(label)) return "undefined";
        return "COLLECTED_DATA[\"" + EscapeJsString(label) + "\"]";
    }

    static string EmitJsExpression(string expr)
    {
        if (string.IsNullOrWhiteSpace(expr)) return "undefined";
        return "(" + expr.Trim() + ")";
    }

    /// <summary>
    /// Emit a "Direct value" — typed wrapper around a raw stored string. The
    /// user types unquoted text; we add JS quoting / parsing / parens here.
    /// </summary>
    static string EmitDirectValue(DirectValueKind kind, string raw)
    {
        switch (kind)
        {
            case DirectValueKind.Number:
                if (string.IsNullOrWhiteSpace(raw)) return "0";
                if (double.TryParse(raw.Trim(), NumberStyles.Float, CultureInfo.InvariantCulture, out double d))
                    return d.ToString("R", CultureInfo.InvariantCulture);
                return "0";
            case DirectValueKind.String:
                return "\"" + EscapeJsString(raw ?? string.Empty) + "\"";
            case DirectValueKind.Bool:
                bool b = !string.IsNullOrEmpty(raw) && raw.Trim().Equals("true", System.StringComparison.OrdinalIgnoreCase);
                return b ? "true" : "false";
            case DirectValueKind.CustomJs:
                return EmitJsExpression(raw);
        }
        return "undefined";
    }

    static string EmitArithmetic(System.Collections.Generic.List<OperandRow> operands)
    {
        if (operands == null || operands.Count == 0) return "undefined";

        string left = EmitOperandLeaf(operands[0].operand);
        for (int i = 1; i < operands.Count; i++)
        {
            string opSym = OpToJs(operands[i - 1].opToNext);
            string right = EmitOperandLeaf(operands[i].operand);
            left = "(" + left + " " + opSym + " " + right + ")";
        }
        return left;
    }

    static string EmitConditional(DataCollectorField f)
    {
        string lhs  = EmitOperandLeaf(f.conditionalLhs);
        string rhs  = EmitOperandLeaf(f.conditionalRhs);
        string thn  = EmitOperandLeaf(f.conditionalThen);
        string els  = EmitOperandLeaf(f.conditionalElse);
        string op   = CmpToJs(f.conditionalOp);
        return "((" + lhs + " " + op + " " + rhs + ") ? " + thn + " : " + els + ")";
    }

    static string EmitOperandLeaf(OperandLeaf leaf)
    {
        if (leaf == null) return "undefined";
        switch (leaf.kind)
        {
            case LeafSourceKind.Collected:       return EmitCollectedAccess(leaf.label);
            case LeafSourceKind.GlobalStateRead: return EmitGlobalStateRead(leaf.stateKey, leaf.stateType);
            case LeafSourceKind.ConditionLookup: return EmitConditionLookup(leaf.label);
            case LeafSourceKind.JsExpression:    return EmitDirectValue(leaf.directValueKind, leaf.jsExpression);
        }
        return "undefined";
    }

    // ─────────────────────────── Helpers ───────────────────────────

    static string CompatType(CckCollectedValueType t)
    {
        switch (t)
        {
            case CckCollectedValueType.Bool:    return "boolean";
            case CckCollectedValueType.Float:   return "float";
            case CckCollectedValueType.Integer: return "integer";
            case CckCollectedValueType.Vector2: return "vector2";
            case CckCollectedValueType.Vector3: return "vector3";
            default: return "boolean";
        }
    }

    static string CompatTypeFromCollected(CollectedValueType t)
    {
        switch (t)
        {
            case CollectedValueType.Bool:    return "boolean";
            case CollectedValueType.Float:   return "float";
            case CollectedValueType.Integer: return "integer";
            case CollectedValueType.Vector2: return "vector2";
            case CollectedValueType.Vector3: return "vector3";
            default: return "boolean";
        }
    }

    static string EqualityCheckFromCollected(CollectedValueType t)
    {
        switch (t)
        {
            case CollectedValueType.Vector2:
                return "({0} === undefined || {0}.x !== {1}.x || {0}.y !== {1}.y)";
            case CollectedValueType.Vector3:
                return "({0} === undefined || {0}.x !== {1}.x || {0}.y !== {1}.y || {0}.z !== {1}.z)";
            default:
                return "{0} !== {1}";
        }
    }

    static string OpToJs(ArithmeticOp op)
    {
        switch (op)
        {
            case ArithmeticOp.Add: return "+";
            case ArithmeticOp.Sub: return "-";
            case ArithmeticOp.Mul: return "*";
            case ArithmeticOp.Div: return "/";
        }
        return "+";
    }

    static string CmpToJs(ComparisonOp op)
    {
        switch (op)
        {
            case ComparisonOp.Eq:    return "===";
            case ComparisonOp.NotEq: return "!==";
            case ComparisonOp.Lt:    return "<";
            case ComparisonOp.LtEq:  return "<=";
            case ComparisonOp.Gt:    return ">";
            case ComparisonOp.GtEq:  return ">=";
        }
        return "===";
    }

    static string EscapeJsString(string s)
    {
        if (string.IsNullOrEmpty(s)) return string.Empty;
        var sb = new StringBuilder(s.Length);
        foreach (char c in s)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"':  sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default:
                    if (c < 0x20) sb.Append(string.Format("\\u{0:x4}", (int)c));
                    else sb.Append(c);
                    break;
            }
        }
        return sb.ToString();
    }

    public static bool IsValidFieldName(string name)
    {
        if (string.IsNullOrEmpty(name)) return false;
        for (int i = 0; i < name.Length; i++)
        {
            char c = name[i];
            bool ok = (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '_' ||
                      (i > 0 && c >= '0' && c <= '9');
            if (!ok) return false;
        }
        return true;
    }
}
#endif
